### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by ramshad-sha** [github/gh-ost#1400]
> This is the place to report a bug, ask a question, or suggest an enhancement.

> This is also the place to make a discussion before creating a PR.

> If this is a bug report, please provide a test case (e.g., your table definition and gh-ost command) and the error output.

> Please use markdown to format code or SQL: https://guides.github.com/features/mastering-markdown/

> Please label the issue on the right (bug, enhancement, question, etc.).

> And please understand if this issue is not addressed immediately or in a timeframe you were expecting.

> Thank you!

```[tasklist]
### Tasks
- [ ] https://github.com/github/gh-ost/pull/1229
- [ ] https://github.com/github/gh-ost/issues/1364
- [ ] https://github.com/github/gh-ost/pull/1383
- [ ] https://github.com/github/gh-ost/pull/1378
- [ ] https://github.com/github/gh-ost/pull/1398
- [ ] https://github.com/github/gh-ost/issues/1397
- [ ] https://github.com/github/gh-ost/issues/1387
- [ ] https://github.com/github/gh-ost/issues/1390
- [ ] https://github.com/github/gh-ost/pull/1367
- [ ] https://github.com/github/gh-ost/pull/1388
- [ ] https://github.com/github/gh-ost/issues/1389
- [ ] https://github.com/github/gh-ost/pull/1355
- [ ] https://github.com/github/gh-ost/issues/1291
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/gh-ost/issues/1291
- [ ] https://github.com/github/gh-ost/pull/1398
- [ ] https://github.com/github/gh-ost/issues/1364
- [ ] https://github.com/github/gh-ost/pull/1383
- [ ] https://github.com/github/gh-ost/pull/1229
- [ ] https://github.com/github/gh-ost/pull/1003
- [ ] https://github.com/github/gh-ost/issues/1397
```

**Comment by ramshad-sha** [comment]
open an issue on the repository&#39;s issues tab

**Comment by ramshad-sha** [comment]
> open an issue on the repository's issues tab
